var NAME = "ISHEE_";
var HP = "568/568";
var STATUS = "STASIS";
var EQUIP = "LIGHTSWORD +6 PHYSatk TUNICOFTHELOSER -2 MAGICdef + 2 PHYSdef";
var LVL = 52;
var EXP = 1578902;
var EXPtonextLVL = 15000;
var MP = "0/295";
var DEX = 17;
var STR = 38;
var DEF = 48;
console.log(" %cPlayer: " + NAME, "color:white;");
console.log(" PlayerHP: " + HP);
console.log(" PlayerMP: " + MP);
console.log(" Player Level: " + LVL );
console.log(" Total EXP: " + EXP);
console.log(" EXP to next LVL= " + EXPtonextLVL);
console.log(" %cPlayerstats:", "color:white;");
console.log(" Strength: " + STR);
console.log(" Defense: " + DEF);
console.log(" Dexterity: " + DEX);
console.log(" Player Status:" + STATUS + " MP critically low ALL STATS lowerd by 10");